project: 
  type: website
  output-dir: docs

website:
  title: "Kevin Gonzalez - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/kevingonmed/DataScience-Programming

  page-footer: 
    border: true
    left: "Kevin Gonzalez 2026©"
    right: 
      - icon: linkedin
        href: https://linkedin.com/in/kevin-gonzalez-
      - icon: github
        href: https://github.com/kevingonmed

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Data Cleansing"
        file: cleansing.qmd
      - text: "Data Exploration"
        file: exploration.qmd
      - text: "Story Telling"
        file: story_telling.qmd
      - text: "Machine Learning"
        file: ml.qmd
      - text: "Full Stack"
        file: full_stack.qmd
      - text: "Competitions"
        file: competition.qmd
  
  sidebar: 
    - title: "Data Cleansing"
      style: "docked"
      background: light
      contents:
        - text: "Data Cleansing"
          file: cleansing.qmd
        - text: "---"
        - text: "Project 1"
          file: Cleansing_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Cleansing_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Cleansing_Projects/project3.qmd
        - text: "---"
    - title: "Data Exploration"
      style: "docked"
      background: light
      contents:
        - text: "Data Exploration"
          file: exploration.qmd
        - text: "---"
        - text: "Project 1"
          file: Cleansing_Exploration/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Cleansing_Exploration/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Cleansing_Exploration/project3.qmd
        - text: "---"
    - title: "Story Telling"
      style: "docked"
      background: light
      contents:
        - text: "Story Telling"
          file: story_telling.qmd
        - text: "---"
        - text: "Project 1"
          file: Story_Telling/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Story_Telling/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Story_Telling/project3.qmd
        - text: "---"
    - title: "Machine Learning"
      style: "docked"
      background: light
      contents:
        - text: "Machine Learning"
          file: ml.qmd
        - text: "---"
        - text: "PromptTrace"
          file: Machine_Learning/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Machine_Learning/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Machine_Learning/project3.qmd
        - text: "---"
    - title: "Full Stack"
      style: "docked"
      background: light
      contents:
        - text: "Full Stack"
          file: full_stack.qmd
        - text: "---"
        - text: "Rexy's Voice"
          file: Full_Stack/project1.qmd
        - text: "---"
        - text: "Course Recommendation App"
          file: Full_Stack/project2.qmd
        - text: "---"
    - title: "Competition"
      style: "docked"
      background: light
      contents:
        - text: "Competition"
          file: competition.qmd
        - text: "---"
        - text: "Apollo 11 Simulator"
          file: Competition/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Competition/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Competition/project3.qmd
        - text: "---"

  
format:  
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
